version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
